default_platform(:android)
platform :android do
 desc "Generate build and upload to firebase"
 lane :build do
#    slack_send(':crossed_fingers: Generating '+ENV['BUILD_TYPE']+' build')
   gradle(
     task: "assemble",
     build_type: ENV['BUILD_TYPE'],
     properties: {
       "android.injected.signing.store.file" => ENV['KEYSTORE_FILE'],
       "android.injected.signing.store.password" => ENV['KEYSTORE_PASS'],
       "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
       "android.injected.signing.key.password" => ENV['KEY_PASS'],
     }
   )
#    slack_send(ENV['BUILD_TYPE']+' Build Successfully completed...:star-struck: \n Uploading to Firebase')
   firebase_app_distribution(
     app: ENV["FIREBASE_APP_ID"],
     release_notes_file: "/Users/bilalhairabtwi/Bilal-Projects/CleanMovies/fastlane/releaseNotes.txt",
     groups: "debug-testing-group",
     firebase_cli_token: ENV['FIREBASE_CI_TOKEN'],
     debug: true
   )
#    slack_send(':tada: Hooooooorrrayyyyy!!! '+ENV['BUILD_TYPE']+' Build is successfully uploaded on Firebase  Distribution!! :dancer::man_dancing:')
  end
end

# def slack_send(msg)
#     slack(
#       message: msg,
#       success: true,
#       channel: '#'+ENV['CHANNEL'],
#       default_payloads: []
#     )
# end